language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
# whitelist
branches:
  only:
    - master
    - rc
script: "./bin/tesla myapp --html hogan --css less --angular --backbone --ember --bootstrap --foundation --gumby --skeleton --jquery --modernizr --zepto"

after_script:
    - cd testapp
    - sudo npm install
    - gulp