language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
# whitelist
branches:
  only:
    - master
script: "./bin/tesla testapp --html hogan --css sass --zepto --foundation --angular"
after_script:
    - cd testapp
    - sudo npm install
    - gulp